[package]
name = "cli_customized_fruit_salad"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
clap = { version = "4.3.4", features = ["derive"] }
csv = "1.1.6"

[lib]
name = "fruit_salad_maker"
path = "src/lib.rs"